spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: configserver
        enabled: true
      fail-fast: true

  application:
    name: api-gateway
