spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: login
          uri: lb://web
          predicates:
            - Path=/perform_login
            - Method=POST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
